Controllers/BrandController.cs
using IcSMP.Models;
using IcSMP.Repositories;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace IcSMP.Controllers
{
    public class BrandController : Controller
    {
        private readonly BrandsRepository _brandsRepository;

        public BrandController(BrandsRepository brandsRepository)
        {
            _brandsRepository = brandsRepository;
        }

        public IActionResult Index()
        {
            var brand = _brandsRepository.GetBrands();
            return View("Index", brand);
        }

        public IActionResult Create()
        {
            return View("Create");
        }

        [HttpPost]
        public IActionResult Create(IFormCollection colletions)
        {
            BrandModel brand = new BrandModel();
            if (ModelState.IsValid)
            {
                TryUpdateModelAsync(brand);
                _brandsRepository.AddBrand(brand);
            }
            return RedirectToAction("Index");
        }

        //EDIT SECTION

        public IActionResult Edit(int id)
        {
            BrandModel brand = _brandsRepository.GetBrandById(id);
            return View("Edit", brand);
        }
        [HttpPost]

        public IActionResult Edit(int id, IFormCollection colletion)
        {
            BrandModel brand = new();
            TryUpdateModelAsync(brand);
            _brandsRepository.Update(brand);

            return RedirectToAction("Index");
        }

        //DETAILS SECTION
        [HttpGet]
        public IActionResult Details(int id)
        {
            BrandModel brand = _brandsRepository.GetBrandById(id);
            return View("Details", brand);
        }

        //DELETE SECTION
        [HttpGet]
        public IActionResult Delete(int id)
        {
            BrandModel brand = _brandsRepository.GetBrandById(id);
            return View("Delete", brand);
        }

        [HttpPost]
        public IActionResult Delete(int id, IFormCollection collection)
        {
            _brandsRepository.Delete(id);
            return RedirectToAction("Index");
        }
    }
}

Controllers/ClientsController.cs
using IcSMP.Models;
using IcSMP.Repositories;
using Microsoft.AspNetCore.Mvc;
using NuGet.Protocol.Core.Types;

namespace IcSMP.Controllers
{
    public class ClientsController : Controller
    {
        private readonly ClientsRepository _clientRepository;
        public ClientsController(ClientsRepository repository) 
        {
            _clientRepository = repository;
        }
        //VIEW SECTION
        public IActionResult Index()
        {
            var clients = _clientRepository.GetClients();
            return View("Index", clients);
        }

        //CREATE SECTION
        public IActionResult Create()
        {
            return View("Create");
        }

        [HttpPost]

        public IActionResult Create(IFormCollection collection)
        {
            ClientModel client = new ClientModel();
            TryUpdateModelAsync(client);
            _clientRepository.AddClient(client);

            return RedirectToAction("Index");
        }

        //EDIT SECTION

        public IActionResult Edit(int id)
        {
            ClientModel client = _clientRepository.GetClientById(id);

            return View("Edit", client);
        }

        [HttpPost]
        public IActionResult Edit(int id, IFormCollection collection)
        {
            ClientModel client = new();
            TryUpdateModelAsync(client);
            _clientRepository.Update(client);

            return RedirectToAction("Index");
        }

        //DETAILS SECTION
        [HttpGet]
        public IActionResult Details(int id)
        {
            ClientModel client = _clientRepository.GetClientById(id);
            return View("Details", client);
        }

        //DELETE SECTION
        [HttpGet]
        public IActionResult Delete(int id)
        {
            ClientModel client = _clientRepository.GetClientById(id);
            return View("Delete", client);
        }


        [HttpPost]
        public IActionResult Delete(int id, IFormCollection collection)
        {
            _clientRepository.Delete(id);
            return RedirectToAction("Index");

        }
    }
}

Controllers/CouriersController.cs
using IcSMP.Repositories;
using Microsoft.AspNetCore.Mvc;
using IcSMP.Models;
using Microsoft.EntityFrameworkCore.Metadata.Internal;

namespace IcSMP.Controllers
{
    public class CouriersController : Controller
    {
        public readonly CouriersRepository _couriersRepository;

        public CouriersController(CouriersRepository couriersRepository)
        {
            _couriersRepository = couriersRepository;
        }

        //VIEW SECTION
        public IActionResult Index()
        {
            var couriers = _couriersRepository.GetCouriers();
            return View("Index", couriers);
        }

        //Create section

        public IActionResult Create()
        {
            return View("Create");
        }
        [HttpPost]
        public IActionResult Create(IFormCollection collection)
        {
            CourierModel courier = new CourierModel();
            if (ModelState.IsValid)
            {
                TryUpdateModelAsync(courier);
                _couriersRepository.AddCourier(courier);
            }
            return RedirectToAction("Index");
        }

        //Edit section
        public IActionResult Edit(int id)
        {
            CourierModel courier = _couriersRepository.GetCourierById(id);
            return View("Edit", courier);
        }

        [HttpPost]
        public IActionResult Edit(int id, IFormCollection collection)
        {
            CourierModel courier = new();
            TryUpdateModelAsync(courier);
            _couriersRepository.Update(courier);

            return RedirectToAction("Index");
        }

        //Details section
       public IActionResult Details(int id)
        {
            CourierModel courier = _couriersRepository.GetCourierById(id);
            return View("Details", courier);
        }

        //Delete section
        [HttpGet]
        public IActionResult Delete(int id)
        {
            CourierModel courier = _couriersRepository.GetCourierById(id);
            return View("Delete", courier);
        }

        [HttpPost]

        public IActionResult Delete(int id, IFormCollection collection)
        {
            _couriersRepository.Delete(id);
            return RedirectToAction("Index");
        }
    }
}

Controllers/ProductsController.cs
using IcSMP.Models;
using IcSMP.Repositories;
using IcSMP.Services;
using IcSMP.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using NuGet.Protocol.Core.Types;
using System.Collections.Generic;

namespace IcSMP.Controllers
{
    public class ProductsController : Controller
    {
        private readonly ProductsRepository _productsRepository;
        private readonly SuppliersRepository _suppliersRepository;
        private readonly CategoriesRepository _categoriesRepository;
        private readonly BrandsRepository _brandsRepository;
        private readonly IMethodsCalculation _methodsCalculation;

        public ProductsController(ProductsRepository productsRepository,
            SuppliersRepository suppliersRepository , 
            CategoriesRepository categoriesRepository,
            BrandsRepository brandsRepository ,
            IMethodsCalculation methodsCalculation)
        {
            _productsRepository = productsRepository;
            _suppliersRepository = suppliersRepository;
            _categoriesRepository = categoriesRepository;
            _methodsCalculation = methodsCalculation;
            _brandsRepository = brandsRepository;
        }

        //VIEW SECTION
        public IActionResult Index()
        {
            var products = _productsRepository.GetProducts();
            var supplier = _suppliersRepository.GetSuppliers();
            var category = _categoriesRepository.GetCategories();
            var brand = _brandsRepository.GetBrands();




            var calculatePriceWithoutVat = _methodsCalculation.calculatePriceWithoutVat;
            var calculateTotal_Sell = _methodsCalculation.calculateTotal_Sell;
            var calculateVat = _methodsCalculation.calculateVat;




            var calculateSumOfColumn_Total_Buy_Whit_Vat_Item = _productsRepository.CalculateAndSave("Buc" , "Buy_Price_Whit_Vat" , "Total_Buy_Whit_Vat_Item");
            var calculateSumOfColumn_TotalBuyItem = _productsRepository.CalculateAndSave("Buc", "BuyPrice", "TotalBuyItem");
            var calculateSumOfColumn_Total_Sell_Item = _productsRepository.CalculateAndSave("Buc", "SellPrice", "Total_Sell_Item");
            var calculateSumOfColumn_Total_Sell_Whit_Vat_Item = _productsRepository.CalculateAndSave("Buc", "SellPriceVat", "Total_Sell_Whit_Vat_Item");


            var calculateSumOfColumn_TotalBuy = _productsRepository.CalculateColumnValueAndSave("TotalBuyItem", "TotalBuy");
            var calculateSumOfColumn_Total_Buy_Whit_Vat = _productsRepository.CalculateColumnValueAndSave("Total_Buy_Whit_Vat_Item", "Total_Buy_Whit_Vat");
            var calculateSumOfColumn_TotalSell = _productsRepository.CalculateColumnValueAndSave("Total_Sell_Item", "TotalSell");
            var calculateSumOfColumn_TotalSellWhitVat = _productsRepository.CalculateColumnValueAndSave("Total_Sell_Whit_Vat_Item", "TotalSellWhitVat");


            var productViewList = new List<ProductViewModel>();
            
            foreach(var product in products)
            {
                var productViewModel = new ProductViewModel()

                {
                    Id = product.Id,
                    Vat = calculateVat(product.Id, product.Buy_Price_Whit_Vat, "Vat"),
//----------------------------------------------------------------------------------------------------------------------------------------------------------------------      

                    Caen = product.Caen,
                    Buc = product.Buc,
                    Description = product.Description,
                    Name = product.Name,
                    ProductNumber = product.ProductNumber,
//----------------------------------------------------------------------------------------------------------------------------------------------------------------------

                    Supplier = supplier?.Where(c => c.Id == product.SupplierId).Select(c => c.CompanyName).FirstOrDefault(),
                    Category = category?.Where(c => c.Id == product.CategoryId).Select(c => c.Name).FirstOrDefault(),
                    Brand = brand?.Where(c => c.Id == product.BrandId).Select(c => c.Name).FirstOrDefault(),
                    SupplierId = product.SupplierId,
                    CategoryId = product.CategoryId,
                    BrandId = product.BrandId,

                    //----------------------------------------------------------------------------------------------------------------------------------------------------------------------

                    BuyPrice = calculatePriceWithoutVat(product.Id , product.Buy_Price_Whit_Vat, "BuyPrice"), // ok
                    
                    Buy_Price_Whit_Vat = product.Buy_Price_Whit_Vat, // ok
                    
                    TotalBuyItem = product.TotalBuyItem, //ok

                    Total_Buy_Whit_Vat_Item = product.Total_Buy_Whit_Vat_Item, //ok
                    
                    TotalBuy = product.TotalBuy,  //ok
                    
                    Total_Buy_Whit_Vat = product.Total_Buy_Whit_Vat ,
                  
//----------------------------------------------------------------------------------------------------------------------------------------------------------------------

                    SellPrice = calculatePriceWithoutVat(product.Id, product.SellPriceVat, "SellPrice"),
                    
                    SellPriceVat = product.SellPriceVat,


                    Total_Sell_Item = product.Total_Sell_Item,  
                    
                    Total_Sell_Whit_Vat_Item = product.Total_Sell_Whit_Vat_Item,
                    
                    TotalSell = product.TotalSell, 
                    
                    TotalSellWhitVat = product.TotalSellWhitVat, 
 //----------------------------------------------------------------------------------------------------------------------------------------------------------------------

                    BuyDate = product.BuyDate,
                };

                productViewList.Add(productViewModel);
            }

            return View("Index" , productViewList);
        }

        //CREATE SECTION

        public IActionResult Create()
        {
            var supplier = _suppliersRepository.GetSuppliers();
            var category = _categoriesRepository.GetCategories();
            var brand = _brandsRepository.GetBrands();

            //var categoryList = category.Select(c => new SelectListItem    ------ Varianta cu Select list
            // {
            //     Text = c.Name.ToString(),
            //     Value = c.Id.ToString()
            // }).ToList();

            //ViewBag.dataCategory = categoryList;

            //var supplierList = supplier.Select(c => new SelectListItem   ------ Varianta cu Select list
            //    Text = c.CompanyName.ToString(),
            //    Value = c.Id.ToString()
            //}).ToList();

            //ViewBag.data = supplierList;
            ViewBag.dataBrand = brand;
            ViewBag.dataCategory = category;
            ViewBag.data = supplier;
            return View("Create");
        }

        [HttpPost]
        public IActionResult Create(IFormCollection collection)
        {
            ProductModel product = new ProductModel(); 
            if(ModelState.IsValid)
            {
                TryUpdateModelAsync(product);
                _productsRepository.AddProduct(product);
            }
            return RedirectToAction("Index");
        }

        //EDIT SECTION
        public IActionResult Edit(int id)
        {
            ProductModel product = _productsRepository.GetProductById(id);
            return View("Edit",product);
        }

        [HttpPost]
        public IActionResult Edit(int id, IFormCollection collection)
        {
            ProductModel product = new();
            TryUpdateModelAsync(product);
            _productsRepository.UpdateProduct(product);

            return RedirectToAction("Index");
        }

        public ProductsRepository Get_productsRepository()
        {
            return _productsRepository;
        }

        //DETAILS SECTION

        [HttpGet]
        public IActionResult Details(int id)
        {
            ProductModel product = _productsRepository.GetProductById(id);
            return View("Details",product);
        }

        //DELETE SECTION

        [HttpGet]
        public IActionResult Delete(int id)
        {
            ProductModel announcement = _productsRepository.GetProductById(id);
            return View("Delete", announcement);
        }

        [HttpPost]
        public IActionResult Delete(int id, IFormCollection collection)
        {

            _productsRepository.DeleteProduct(id);
            return RedirectToAction("Index");
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - IcSMP</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/SiteStructure.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/TextColor.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/IcSMP.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/View.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/Animations.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/font-awesome/css/all.css" />
</head>
<body>
    @if (User.Identity.IsAuthenticated)
    {
        <header>
            <nav class="navbar navbar-expand-sm navbar-toggleable-sm mb-3 nav-bar-decoration">
                <div class="container-fluid">
                    <button class="navbar-toggler custom-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                        <img src="./Asset/Catalin-logo1.png" alt="company logo" class="logo-nav" />
                        <a class="nav-link puls" asp-area="" asp-controller="Home" asp-action="Index">
                            <i class="fa-solid fa-house-user"></i>
                            IcSMP
                        </a>
                        <ul class="navbar-nav flex-grow-1 justify-content-center nav-bar-spacing">
                            <li class="nav-item margin-item">
                                <a class="nav-link" asp-area="" asp-controller="Categories" asp-action="Index">
                                    <i class="fa-solid fa-folder-tree"></i>
                                    Categories
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Products" asp-action="Index">
                                    <i class="fa-solid fa-hand-holding-dollar"></i>
                                    Stock
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Clients" asp-action="Index">
                                    <i class="fa-solid fa-person-circle-plus"></i>
                                    Clients Db
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Suppliers" asp-action="Index">
                                    <i class="fa-solid fa-box-open"></i>
                                    Suppliers
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Couriers" asp-action="Index">
                                    <i class="fa-solid fa-truck-front"></i>
                                    Logistics
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Brand" asp-action="Index">
                                    <i class="fa-solid fa-truck-front"></i>
                                    Brands
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Privacy">
                                    <i class="fa-solid fa-users-gear"></i>
                                    About Us
                                </a>
                            </li>
                        </ul>
                        <a class="nav-link puls" asp-area="" asp-controller="AccountAuth0" asp-action="Logout">
                            <i class="fa-solid fa-power-off"></i>
                            Log out
                        </a>

                    </div>
                </div>
            </nav>
        </header>
        <div class="container">

            <main role="main" class="pb-3">
                @RenderBody()

            </main>
        </div>
    }
    else
    {
        <header>
            <nav class="navbar navbar-expand-sm navbar-toggleable-sm mb-3 nav-bar-decoration">
                <div class="container-fluid login-start">
                    <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                        <a class="nav-link puls login-start">
                            IcSMP
                        </a>
                    </div>
                    <div>
                        <h1>Iordache Catalin Stocks Management Program</h1>
                    </div>
                </div>
            </nav>
        </header>
        <div class="container login-start">
            <button>
                <i class="fa-solid fa-computer" style="font-size:200px"></i>
                <div>
                    <a class="puls" asp-area="" asp-controller="AccountAuth0" asp-action="Login">
                        <i class="fa-solid fa-right-to-bracket"> </i>
                        Please login
                    </a>
                </div>
            </button>

            <main role="main" class="pb-3" style="display:none;">
                @RenderBody()

            </main>
        </div>
    }

    <footer class="text-muted footer-bar-decoration">
        <div class="container">
            <span class="footer-item">
                &copy; 2023 - IcSMP -
            </span>
            <a class="footer-item"  asp-area="" asp-controller="Home" asp-action="Privacy">About Us</a>
            
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>